edit_uri: ""
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sentinel-official
    - icon: fontawesome/brands/medium
      link: https://sentinel.medium.com
    - icon: fontawesome/brands/telegram
      link: https://t.me/sentinel_co
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Sentinel_co
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
nav:
  - Home: index.md
  - Modules:
      - Deposit:
          - Introduction: modules/deposit/introduction.md
          - Types: modules/deposit/types.md
          - Keeper: modules/deposit/keeper.md
          - Messages: modules/deposit/messages.md
          - Queries: modules/deposit/queries.md
          - ABCI: modules/deposit/ABCI.md
          - Commands: modules/deposit/commands.md
      - Provider:
          - Introduction: modules/provider/introduction.md
          - Types: modules/provider/types.md
          - Keeper: modules/provider/keeper.md
          - Messages: modules/provider/messages.md
          - Queries: modules/provider/queries.md
          - ABCI: modules/provider/ABCI.md
          - Commands: modules/provider/commands.md
      - Node:
          - Introduction: modules/node/introduction.md
          - Types: modules/node/types.md
          - Keeper: modules/node/keeper.md
          - Messages: modules/node/messages.md
          - Queries: modules/node/queries.md
          - ABCI: modules/node/ABCI.md
          - Commands: modules/node/commands.md
      - Plan:
          - Introduction: modules/plan/introduction.md
          - Types: modules/plan/types.md
          - Keeper: modules/plan/keeper.md
          - Messages: modules/plan/messages.md
          - Queries: modules/plan/queries.md
          - ABCI: modules/plan/ABCI.md
          - Commands: modules/plan/commands.md
      - Subscription:
          - Introduction: modules/subscription/introduction.md
          - Types: modules/subscription/types.md
          - Keeper: modules/subscription/keeper.md
          - Messages: modules/subscription/messages.md
          - Queries: modules/subscription/queries.md
          - ABCI: modules/subscription/ABCI.md
          - Commands: modules/subscription/commands.md
      - Session:
          - Introduction: modules/session/introduction.md
          - Types: modules/session/types.md
          - Keeper: modules/session/keeper.md
          - Messages: modules/session/messages.md
          - Queries: modules/session/queries.md
          - ABCI: modules/session/ABCI.md
          - Commands: modules/session/commands.md
  - dVPN node:
      - Setup: nodes/dVPN/setup.md
      - Configuration:
          - Application: nodes/dVPN/configuration/application.md
          - WireGuard: nodes/dVPN/configuration/wireguard.md
      - Start: nodes/dVPN/start.md
      - Troubleshoot: nodes/dVPN/troubleshoot.md
      - API: nodes/dVPN/API.md
  - CLI client:
      - Keys: clients/CLI/keys.md
      - Queries: clients/CLI/queries.md
      - Transactions: clients/CLI/transactions.md
      - VPN: clients/CLI/VPN.md
      - API: clients/CLI/API.md
plugins:
  - minify:
      minify_html: true
  - search
site_name: Sentinel Docs
site_url: https://docs.sentinel.co
strict: true
repo_name: sentinel-official/docs
repo_url: https://github.com/sentinel-official/docs
theme:
  favicon: assets/favicon.svg
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  logo: assets/logo.svg
  name: material
  palette:
    primary: black
